In [1]:
from numpy.random import seed
seed(1)

In [2]:
import numpy as np
import pandas as pd

In [3]:
import tensorflow
tensorflow.keras.__version__

'2.4.0'

In [11]:
homes = pd.read_excel('final project reduced.xlsx')
homes.head()

,zip,prop_latitude,prop_longitude,prop_yrbld,prop_landsqft,prop_bldsqft,prop_livingsqft,prop_saledate,prop_saleamt,prop_saledate_prior,prop_saleamt_prior,prop_mtgamt_prior,current financing percent,Prior Financing percent,prop_mtgamt,Duration prior,percentage increase/decrease- prior
0,46217,39.655831,-86.218025,2011,6926.0,2999.0,2399.0,2017-05-08,178407,2011-03-30,156542,154993,0.990101,0.990105,176641.0,2231,0.122557
1,46268,39.874484,-86.247279,1995,11069.0,3412.0,2350.0,2017-05-18,257500,2007-01-16,206150,155000,0.800000,0.751880,206000.0,3775,0.199417
2,46217,39.671222,-86.161665,1955,18992.0,2796.0,2152.0,2018-06-15,158980,2015-02-17,159125,127300,0.990099,0.800000,157406.0,1214,-0.000912
3,46239,39.694670,-86.013174,2006,10759.0,4350.0,2680.0,2016-05-20,293312,2006-08-17,359146,270035,0.800001,0.751881,234650.0,3564,-0.224450
4,46227,39.670611,-86.125501,1957,13983.0,2966.0,1336.0,2016-03-14,122127,2002-10-23,137056,103050,0.990100,0.751882,120918.0,4891,-0.122242

In [12]:
homes = homes.drop(columns=['prop_latitude', 'prop_longitude', 'prop_saledate', 'prop_saleamt', 'prop_saledate_prior', 'prop_saleamt_prior', 'prop_mtgamt_prior', 'current financing percent', 'prop_mtgamt'])
homes.head()

,zip,prop_yrbld,prop_landsqft,prop_bldsqft,prop_livingsqft,Prior Financing percent,Duration prior,percentage increase/decrease- prior
0,46217,2011,6926.0,2999.0,2399.0,0.990105,2231,0.122557
1,46268,1995,11069.0,3412.0,2350.0,0.751880,3775,0.199417
2,46217,1955,18992.0,2796.0,2152.0,0.800000,1214,-0.000912
3,46239,2006,10759.0,4350.0,2680.0,0.751881,3564,-0.224450
4,46227,1957,13983.0,2966.0,1336.0,0.751882,4891,-0.122242

In [13]:
homes.dropna()
homes.head()

,zip,prop_yrbld,prop_landsqft,prop_bldsqft,prop_livingsqft,Prior Financing percent,Duration prior,percentage increase/decrease- prior
0,46217,2011,6926.0,2999.0,2399.0,0.990105,2231,0.122557
1,46268,1995,11069.0,3412.0,2350.0,0.751880,3775,0.199417
2,46217,1955,18992.0,2796.0,2152.0,0.800000,1214,-0.000912
3,46239,2006,10759.0,4350.0,2680.0,0.751881,3564,-0.224450
4,46227,1957,13983.0,2966.0,1336.0,0.751882,4891,-0.122242

In [15]:
X = homes.drop("Duration prior", axis=1)
y = homes["Duration prior"]
print(X.shape, y.shape)

(18354, 7) (18354,)

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [21]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [24]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=20))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [25]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [26]:
 model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 100)               2100
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 202
=================================================================
Total params: 12,402
Trainable params: 12,402
Non-trainable params: 0
_________________________________________________________________

In [27]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

NameError: name 'y_train_categorical' is not defined